### ISSUE TITLE
Failed to install geodiff from pip3

### ISSUE THREAD

**Issue by VitorVieiraZ** [MerginMaps/geodiff#212]
In macbook air m2, mac version 14.2.1, failed to install geodiff from pip3, even after running command `python -m pip install --upgrade pip`.

```     [17/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqliteutils.cpp.o
      FAILED: CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqliteutils.cpp.o
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DGPKG_HAVE_CONFIG_H -DSQLITE_CORE -Dpygeodiff_2_0_2_python_EXPORTS -I/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/geodiff/src -I/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/geodiff/src/3rdparty -I/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/geodiff/src/drivers -I/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/_skbuild/macosx-14.0-arm64-3.9/cmake-build -I/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/_skbuild/macosx-14.0-arm64-3.9/cmake-build/external/libgpkg-0822c5cba7e1ac2c2806e445e5f5dd2f0d0a18b4/gpkg -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=14.0 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqliteutils.cpp.o -MF CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqliteutils.cpp.o.d -o CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqliteutils.cpp.o -c /private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/geodiff/src/drivers/sqliteutils.cpp
      /private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/geodiff/src/drivers/sqliteutils.cpp:229:12: error: use of undeclared identifier 'sqlite3_enable_load_extension'
        int rc = sqlite3_enable_load_extension( db->get(), 1 );
                 ^
      1 error generated.
      [18/32] Building C object CMakeFiles/pygeodiff-2.0.2-python.dir/external/libgpkg-0822c5cba7e1ac2c2806e445e5f5dd2f0d0a18b4/gpkg/spl_geom.c.o
      [19/32] Building C object CMakeFiles/pygeodiff-2.0.2-python.dir/external/libgpkg-0822c5cba7e1ac2c2806e445e5f5dd2f0d0a18b4/gpkg/sql.c.o
      [20/32] Building C object CMakeFiles/pygeodiff-2.0.2-python.dir/external/libgpkg-0822c5cba7e1ac2c2806e445e5f5dd2f0d0a18b4/gpkg/spatialdb.c.o
      [21/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/tableschema.cpp.o
      [22/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/changesetconcat.cpp.o
      [23/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/geodiffrebase.cpp.o
      [24/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/changesetutils.cpp.o
      [25/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/geodiff.cpp.o
      [26/32] Building CXX object CMakeFiles/pygeodiff-2.0.2-python.dir/src/drivers/sqlitedriver.cpp.o
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-build-env-qct6wvji/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 674, in setup
          cmkr.make(make_args, install_target=cmake_install_target, env=env)
        File "/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-build-env-qct6wvji/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 697, in make
          self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
        File "/private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-build-env-qct6wvji/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 742, in make_impl
          raise SKBuildError(msg)
      
      An error occurred while building with CMake.
        Command:
          /private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-build-env-qct6wvji/overlay/lib/python3.9/site-packages/cmake/data/bin/cmake --build . --target install --config Release --
        Install target:
          install
        Source directory:
          /private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba
        Working directory:
          /private/var/folders/5g/vwg72l411dn9pp9k6yw0zk0c0000gn/T/pip-install-39ruw6wq/pygeodiff_8ed0aaba0e504cfabd256a351f1de2ba/_skbuild/macosx-14.0-arm64-3.9/cmake-build
      Please check the install target is valid and see CMake's output for more information.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pygeodiff
Failed to build pygeodiff
ERROR: Could not build wheels for pygeodiff, which is required to install pyproject.toml-based projects
```

**Comment by wonder-sk** [comment]
Looks like the same issue as this one: https://github.com/MerginMaps/python-api-client/issues/164

**Comment by PeterPetrik** [comment]
Yes, also if we release new geodiff with https://github.com/MerginMaps/geodiff/pull/211 it will be fixed since we will ship M1/M2 binaries
